apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  annotations:
  labels:
    discovered_by: kubernetesplugin
  name: default-session-affinity-app-80
  namespace: gloo-system
spec:
  upstreamSpec:
    kube:
      selector:
        name: session-affinity-app
      serviceName: session-affinity-app
      serviceNamespace: default
      servicePort: 80
    ### The manual (non-discovered) config starts here
    loadBalancerConfig:
      ringHash:
        ringHashConfig:
          maximumRingSize: "200"
          minimumRingSize: "10"
    ### (end)
